name = "is-homeable"
description = "Exposes a homing procedure"
requires = ["has-position"]

[method]

[method.home]
description = """
Initiates the homing procedure.
The daemon will report as busy during the homing procedure.
 After the homing procedure is complete, the daemon will return to the current destination.
"""
