protocol = "is-daemon"
doc = "Core trait common to all yaq daemons."
requires = []

[config]
port.type = "integer"
port.description = "TCP port for daemon to occupy."
serial.type = "string"
serial.default = "NULL"
serial.description = "Serial number for the particular device represented by the daemon"
make.type = "String"
make.default = "NULL"
model.type = "String"
model.default = "NULL"

[messages]

[messages.busy]
doc = "Returns true if daemon is currently busy."
response = "boolean"

[messages.id]
doc = """
JSON object with information to identify the daemon, including name, kind, make, model, serial.
"""
response = {type="map", "values"=["null", "string"]}

[messages.get_config_filepath]
doc = """
String representing the absolute filepath of the configuration file on the host machine.
"""
response = "string"

[messages.get_config]
doc = """
Full configuration for the individual daemon as defined in the TOML file.
This includes defaults and shared settings not directly specified in the daemon-specific TOML table.
"""
response = "string"

[messages.get_traits]
doc = "Get a full list of the daemon traits."
response = {"type"="array", "items"="string"}

[messages.shutdown]
doc = "Cleanly shutdown (or restart) daemon."
request = [
  {"name"="restart", "type"="boolean", "default"="false"},
]

[messages.get_version]
doc = "Get version of the running daemon"
response = "string"


[messages.get_state]
doc = "Get version of the running daemon"
response = "string"